config/routes.rb
Rails.application.routes.draw do
  get '/login', to: 'sessions#new'
  match '/login', to: 'sessions#create', via: [:post, :patch, :put]
  delete '/logout', to: 'sessions#destroy'

  namespace :admin do
    resources :users
  end
  root to: 'events#index'
  resources :events
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
    validates :name, presence: true, length: { maximum: 30 }
    validate :validate_name_not_including_comma


    belongs_to :user

    scope :recent, -> { order(created_at: :desc) }

    def validate_name_not_including_comma
        errors.add(:name, 'にカンマを含めることはできません。') if name&.include?(',')
    end
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    validates :name, presence: true
    validates :email, presence: true, uniqueness: true

    has_many :events
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to admin_user_url(@user), notice: "ユーザ「#{@user.name}」を登録しました。"
    else
      render :new
    end
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to admin_user_url(@user), notice: "ユーザ「#{@user.name}」を更新しました。"
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_users_url, notice: "ユーザ「#{@user.name}」を削除しました。"
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :admin, :password, :password_confirmation)
  end

  def require_admin
    redirect_to root_url unless current_user.admin?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user
    before_action :login_required

    private

    def current_user
        @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
    end

    def login_required
        redirect_to login_url unless current_user
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = current_user.events.order(created_at: :desc)

    respond_to do |format|
      format.html # index.html.erb
      format.xml { render :xml => @events }
      format.json { render :json => @events }
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = current_user.events.find(params[:id])
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
    @event = current_user.events.find(params[:id])
  end

  # POST /events
  # POST /events.json
  def create
    @event = current_user.events.new(event_params)

    respond_to do |format|
      if @event.save
        logger.debug "event: #{@event.attributes.inspect}"
        format.html { redirect_to @event, notice: "スケジュール「#{@event.name}」を登録しました。" }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    @event = current_user.events.find(params[:id])
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'スケジュールが更新されました。' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event = current_user.events.find(params[:id])
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'スケジュールを削除しました。' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = current_user.events.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:company, :name, :description, :start, :end)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required
  def new
  end

  def create
    user = User.find_by(email: session_params[:email])

    if user&.authenticate(session_params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: 'ログインしました。'
    else
      render :new
    end
  end

  def destroy
    reset_session
    redirect_to root_url, notice: 'ログアウトしました。'
  end

private
  def session_params
    params.require(:session).permit(:email, :password)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/admin/users/_form.html.slim
- if user.errors.present?
  ul#error_explanation
    - user.errors.full_messages.each do |message|
      li= message

= form_with model: [:admin, user], local: true do |f|
  .form-group
    = f.label :name, '名前'
    =f.text_field :name, class: 'form-control'
  .form-group
    = f.label :email, 'メールアドレス'
    = f.text_field :email, class: 'form-control'
  .form-check
    = f.label :admin, class: 'form-check-label' do
      =f.check_box :admin, class: 'form-check-input'
      | 管理者権限
  .form-group
    = f.label :password, 'パスワード'
    = f.password_field :password, class: 'form-control'
  .form-group
    = f.label :password_confirmation, 'パスワード（確認）'
    = f.password_field :password_confirmation, class: 'form-control'
  = f.submit nil, class: 'btn btn-sm btn-outline-primary'

app/views/admin/users/edit.html.slim
h1 ユーザ編集

.nav.justify-content-end
  = link_to '一覧', admin_users_path, class: 'nav-link btn btn-outline-secondary mr-3'

= render partial: 'form', locals: { user: @user }

app/views/admin/users/index.html.slim
h1 ユーザ一覧

= link_to '新規登録', new_admin_user_path, class: 'btn btn-sm btn-outline-primary'

.md-3
table.table.table-hover
  thead.thead-default
    tr
      th= User.human_attribute_name(:name)
      th= User.human_attribute_name(:email)
      th= User.human_attribute_name(:admin)
      th= User.human_attribute_name(:created_at)
      th= User.human_attribute_name(:updated_at)
      th
  tbody
    - @users.each do |user|
      tr
        td= user.name
        td= user.email
        td= user.admin? ? 'あり' : 'なし'
        td= user.created_at
        td= user.updated_at
        td
          = link_to '詳細', admin_user_path(user), class: 'btn btn-outline-primary mr-3'
          = link_to '編集', edit_admin_user_path(user), class: 'btn btn-outline-primary mr-3'
          = link_to '削除', [:admin, user], method: :delete, data: { confirm: "ユーザ「#{user.name}」を削除します。よろしいですか？" }, class: 'btn btn-danger'

app/views/admin/users/new.html.slim
h1 ユーザ登録

.nav.justify-content-end
  = link_to '一覧', admin_users_path, class: 'nav-link btn btn-outline-secondary mr-3'

= render partial: 'form', locals: { user: @user }

app/views/admin/users/show.html.slim
h1 ユーザ詳細

.nav.justify-content-end
  = link_to '一覧', admin_users_path, class: 'nav-link btn btn-outline-secondary mr-3'
table.table.table-hover
  thead.thead-default
    tr
      th= User.human_attribute_name(:id)
      td= @user.id
    tr
      th= User.human_attribute_name(:name)
      td= @user.name
    tr
      th= User.human_attribute_name(:email)
      td= @user.email
    tr
      th= User.human_attribute_name(:admin)
      td= @user.admin? ? 'あり' : 'なし'
    tr
      th= User.human_attribute_name(:created_at)
      td= @user.created_at
    tr
      th= User.human_attribute_name(:updated_at)
      td= @user.updated_at

= link_to '編集', edit_admin_user_path, class: 'btn btn-outline-primary'
= link_to '削除', [:admin, @user], method: :delete, data: { confirm: "ユーザ「#{@user.name}」を削除します。よろしいですか？" }, class: 'btn btn-danger'

app/views/events/_form.html.slim
- if event.errors.present?
  ul#error_explanation
    - event.errors.full_messages.each do |message|
      li = message

= form_with model: event, local: true do |f|

  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control', id: 'event_name'
  .form-group
    = f.label :description
    = f.text_area :description, rows: 5, class: 'form-control', id: 'event_description'
  .form-group
    = f.label :start
    = f.datetime_select :start, {}, class: 'form-control form-control-inline'
  .form-group
    = f.label :end
    = f.datetime_select :end, {}, class: 'form-control form-control-inline'
  = f.submit nil, class: 'btn btn-outline-primary'

app/views/events/edit.html.slim
h1　スケジュール編集
.nav.justify-content-end
  = link_to '一覧', events_path, class: 'nav-link btn btn-outline-secondary mr-3'

= render partial: 'form', locals: { event: @event }

app/views/events/index.html.slim
.nav.justify-content-start
  = link_to '新規登録', new_event_path, class: 'btn btn-outline-primary'
.nav.justify-content-end
  = link_to '一覧', events_path, class: 'nav-link btn btn-outline-secondary mr-3'
#calendar

.md-3
table.table.table-hover
  thead.thead-default
    tr
      
      th= Event.human_attribute_name(:name)
      th= Event.human_attribute_name(:description)
      th= Event.human_attribute_name(:start)
      th= Event.human_attribute_name(:end)
      th 
  tbody
    - @events.each do |event|
      tr
        
        td= event.name
        td= event.description
        td= event.start
        td= event.end
        td
          = link_to '詳細', event_path(event), class: 'btn btn-sm btn-outline-primary mr-1'
          = link_to '編集', edit_event_path(event), class: 'btn btn-sm btn-outline-primary mr-1'
          = link_to '削除', event, method: :delete, data: { confirm: "タイトル「#{event.name}」を削除します。よろしいですか？" }, class: 'btn btn-sm btn-danger mr-1'
br

app/views/events/new.html.slim
h1 新規スケジュール
.nav.justify-content-end
  = link_to '一覧', events_path, class: 'nav-link btn btn-outline-secondary mr-3'

= render partial: 'form', locals: { event: @event }

app/views/events/show.html.slim
h1 スケジュール詳細
.nav.justify-content-end
  = link_to '一覧', events_path, class: 'nav-link btn btn-outline-secondary mr-3'

table.table.table-hover
  tbody
    tr
      th= Event.human_attribute_name(:id)
      td= @event.id
    
    tr
      th= Event.human_attribute_name(:name)
      td= @event.name
    tr
      th= Event.human_attribute_name(:description)
      td= auto_link(simple_format(h(@event.description), {}, sanitize: false, wrapper_tag: "div"))
    tr
      th= Event.human_attribute_name(:start)
      td= @event.start
    tr
      th= Event.human_attribute_name(:end)
      td= @event.end
    
= link_to '編集', edit_event_path(@event), class: 'btn btn-sm btn-outline-primary mr-3'
= link_to '削除', @event, method: :delete, data: { confirm: "タイトル「#{@event.name}」を削除します。よろしいですか？" }, class: 'btn btn-sm btn-danger mr-1'

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Taskleaf
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    .app-title.navbar.navbar-expand-md.navbar-light.bg-light
      .navbar-brand Schedule

      ul.navbar-nav.ml-auto
        - if current_user
          li.nav-item= link_to 'スケジュール', events_path, class: 'nav-link'
          - if current_user.admin?
          li.nav-item= link_to 'ユーザ一覧', admin_users_path, class: 'nav-link'
          li.nav-item= link_to 'ログアウト', logout_path, method: :delete, class: 'nav-link'
        - else
          li.nav-item= link_to 'ログイン', login_path, class: 'nav-link'
    .container
      - if flash.notice.present?
        .alert.alert-success= flash.notice
      = yield